version: "3.3"

services:
  rmq:
    build: ./rmq
    network_mode: bridge
    ports:
      - 15672:15672
      - 5672:5672

  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - rmq
    links:
      - rmq
    environment:
      - RMQ_URL=amqp://student:qwerty@rmq:5672/
    restart: always
    entrypoint: python3 -u api/main.py
    network_mode: bridge

  consumer:
    build: .
    depends_on:
      - rmq
    links:
      - rmq
      - api
    environment:
      - RMQ_URL=amqp://student:qwerty@rmq:5672/
      - API_URL=http://api:8080/update_task_status_api/
      - QUEUE_NAME=test_direct
      - EXCHANGE_NAME=to_direct

    restart: always
    entrypoint: python3 -u consumer/main.py
    network_mode: bridge
