version: "3.3"

services:
  rmq:
    build: ./rmq
    ports:
      - 15672:15672
      - 5672:5672

  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - rmq
    environment:
      - RMQ_URL=amqp://student:qwerty@rmq:5672/
    restart: always
    entrypoint: python3 -u api/main.py

  consumer:
    build: .
    depends_on:
      - rmq
    environment:
      - RMQ_URL=amqp://student:qwerty@rmq:5672/
      - API_URL=http://api:8080/update_task_status_api/
      - QUEUE_NAME=test_direct
      - EXCHANGE_NAME=to_direct

    restart: always
    entrypoint: python3 -u consumer/main.py

  celery_worker:
    build: .
    depends_on:
      - rmq
      - api
    environment:
      - RMQ_URL=amqp://student:qwerty@rmq:5672/
      - API_URL=http://api:8080/update_task_status_api/
    restart: always
    working_dir: /code/api
    entrypoint: celery -A celery_app worker --loglevel=info --concurrency=3
